apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: jenkins build actions
inputs:
  url:  # id of input
    description: 'jenkins url'
    required: true
  username:  # id of input
    description: 'user name'
    required: true
  token:  # id of input
    description: 'token'
    required: true
  job-name:  # id of input
    description: 'job name'
    required: true
  test-type:  # id of input
    description: 'test type'
    default: ''
  test-result-location:  # id of input
    description: 'test result location'
    default: ''
  parameters:  # id of input
    description: 'parameters as json'
    default: '{}'

outputs:
  jenkins_output:
    value: ${{ steps.invoke-jenkins-job.outputs.jenkins_output_var }}
    description: Jenkins variable output
    
runs:
  using: composite
  steps:
    - id: invoke-jenkins-job
      name: invoke-jenkins-job
      uses: docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/jenkins-actions:main-8db94b14cfe63327da40bd0ef82ee97c6cd429fc
      shell: sh
      env:
        CONFIG_JSON: '{"metaInfo":{"url":"${{ inputs.url }}","toolType":"JENKINS","username":"${{ inputs.username }}","token":"${{ inputs.token }}","jobName":"${{ inputs.job-name }}","testType":"${{ inputs.test-type }}","fileName":"${{ inputs.test-result-location }}","parameters":${{ inputs.parameters }},"commitId":"${{ cloudbees.scm.sha }}"}}'
        RUN_ID: ${{ cloudbees.run_id }}
        JOB_ID: ${{ job.id }}
        STEP_ID: ${{step.internal.id}}
        DNS_URL: ${{ cloudbees.api.url }}
        JWT_TOKEN: ${{ cloudbees.api.token }}
      run: |
        set -x
        cd /app
        ./jenkins_actions_app invoke -b $CONFIG_JSON
